[package]
name = "crw-client"
version = "0.1.1"
authors = ["bragaz <leo.braga95@gmail.com"]
edition = "2018"
description = "Client package of cosmos-rust-wallet to broadcast tx and query data from a cosmos based blockchain"
license = "Apache-2.0"
repository = "https://github.com/forbole/cosmos-rust-wallet"
keywords = ["blockchain", "cosmos", "cosmos-rust-wallet"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cosmos-sdk-proto = { version = "0.3.0"}
prost = { version = "0.7.0"}
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.62" }
crw-types = { path = "../../packages/crw-types", version = "0.1.0" }
wasm-bindgen = { version = "0.2.70", features = ["serde-serialize"]}
wasm-bindgen-futures = { version = "0.4.21"}

[dev-dependencies]
actix-rt = "2.0.2"
prost-types = {version = "0.7"}
crw-wallet = { path = "../../packages/crw-wallet", version = "0.1.0" }
wasm-bindgen-test = "0.3.20"
