[package]
name = "crw-preferences"
version = "0.1.0"
authors = ["Manuel <manuel.turetta94@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cocoon = "0.2.3"
serde = "1.0.126"
serde_json = "1.0.64"
#getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.70"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
